# Generated by Django 6.0.6 on 2026-06-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
